import { STATUS_TO_CATEGORY, type OrderData } from "./order-types";

export const MOCK_ORDERS: OrderData[] = [
  // --- Active orders ---
  {
    orderId: "CUI398",
    orderType: "laundry",
    status: "order_received",
    listTimestamp: "23 Apr 2026, 09:14 AM",
    pickupLocation: "Apt 1402, Marina Heights, Dubai Marina",
    pickupWindow: "Tomorrow · 8:00 – 10:00 AM",
    dropoffWindow: "Sun · 6:00 – 8:00 PM",
    pickupNote: "Pickup at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "23 Apr, 9:14 am",
      partially_delivered: "23 Apr, 6:42 pm",
    },
    leaveBagsOutside: true,
    cancellable: true,
  },
  {
    orderId: "SHB201",
    orderType: "shoe_bag",
    status: "items_sorted",
    listTimestamp: "22 Apr 2026, 03:48 PM",
    pickupLocation: "Tower B, Jumeirah Beach Residence",
    pickupWindow: "Mon · 7:00 – 9:00 AM",
    dropoffWindow: "Fri · 5:00 – 7:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "20 Apr, 6:02 pm",
      collected: "21 Apr, 7:48 am",
      items_in_process: "21 Apr, 1:12 pm",
    },
  },
  {
    orderId: "TFY104",
    orderType: "finery",
    status: "pickup_completed",
    listTimestamp: "22 Apr 2026, 11:02 AM",
    pickupLocation: "Villa 27, Emirates Hills",
    pickupWindow: "Today · 10:00 AM – 12:00 PM",
    dropoffWindow: "Wed · 2:00 – 4:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "21 Apr, 8:30 pm",
      collected: "22 Apr, 11:02 am",
    },
  },
  {
    orderId: "CUI376",
    orderType: "laundry",
    status: "items_pending_approval",
    listTimestamp: "21 Apr 2026, 06:30 PM",
    pickupLocation: "Apt 905, Boulevard Plaza, Downtown",
    pickupWindow: "Mon · 6:00 – 8:00 PM",
    dropoffWindow: "Thu · 6:00 – 8:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "19 Apr, 5:40 pm",
      collected: "20 Apr, 7:55 am",
      items_in_process: "20 Apr, 1:20 pm",
    },
    itemsAwaitingApproval: 2,
    approvalDeadline: "2h 5m left to action",
  },
  {
    orderId: "CUI401",
    orderType: "laundry",
    status: "payment_failed",
    listTimestamp: "Today, 10:24 am",
    pickupLocation: "Apt 2208, Index Tower, DIFC",
    pickupWindow: "20 Apr · 7:00 – 9:00 AM",
    dropoffWindow: "Today · 4:00 – 6:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "19 Apr, 6:48 pm",
      collected: "20 Apr, 7:32 am",
      items_in_process: "20 Apr, 12:40 pm",
      delivery_today: "Today, 9:10 am",
      driver_on_the_way: "Today, 10:18 am",
    },
    amountDue: "AED 145.00 due",
  },
  {
    orderId: "TFY108",
    orderType: "finery",
    status: "dropoff_in_progress",
    listTimestamp: "Today, 9:42 am",
    pickupLocation: "Villa 8, Al Wasl Road, Jumeirah 1",
    pickupWindow: "18 Apr · 9:00 – 11:00 AM",
    dropoffWindow: "Today · before 6:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Hand to resident",
    stageTimestamps: {
      received: "17 Apr, 7:15 pm",
      collected: "18 Apr, 9:28 am",
      items_in_process: "18 Apr, 1:52 pm",
      delivery_today: "Today, 8:30 am",
      driver_on_the_way: "Today, 9:42 am",
    },
  },
  {
    orderId: "SHB205",
    orderType: "shoe_bag",
    status: "pending_items_delivery_partial",
    listTimestamp: "Yesterday, 6:42 pm",
    pickupLocation: "Apt 1810, Address Sky View, Downtown",
    pickupWindow: "16 Apr · 8:00 – 10:00 AM",
    dropoffWindow: "Tomorrow · 5:00 – 7:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "15 Apr, 8:02 pm",
      collected: "16 Apr, 8:14 am",
      items_in_process: "16 Apr, 1:26 pm",
      approval_completed: "18 Apr, 11:12 am",
      delivery_today: "Yesterday, 4:30 pm",
      partially_delivered: "Yesterday, 6:42 pm",
    },
    itemsPending: 2,
  },
  {
    orderId: "PND472",
    orderType: "shoe_bag",
    status: "pending_items_delivery_followup",
    listTimestamp: "Today, 5:30 pm",
    pickupLocation: "Apt 1810, Address Sky View, Downtown",
    pickupWindow: "16 Apr · 8:00 – 10:00 AM",
    dropoffWindow: "Today · 5:00 – 7:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "15 Apr, 8:02 pm",
      collected: "16 Apr, 8:14 am",
      items_in_process: "16 Apr, 1:26 pm",
      approval_completed: "18 Apr, 11:12 am",
      delivery_today: "Yesterday, 4:30 pm",
      partially_delivered: "Yesterday, 6:42 pm",
    },
    itemsPending: 2,
  },
  {
    orderId: "CUI403",
    orderType: "laundry",
    status: "dropoff_today",
    listTimestamp: "Today, 8:15 am",
    pickupLocation: "Apt 604, The Greens, Al Thayyal",
    pickupWindow: "20 Apr · 7:00 – 9:00 AM",
    dropoffWindow: "Today · 5:00 – 7:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "19 Apr, 7:54 pm",
      collected: "20 Apr, 7:46 am",
      items_in_process: "20 Apr, 12:18 pm",
      delivery_today: "Today, 8:15 am",
    },
  },
  {
    orderId: "CUI410",
    orderType: "laundry",
    status: "pickup_assigned",
    listTimestamp: "Today, 12:18 am",
    pickupLocation: "Apt 305, Burj Vista, Downtown",
    pickupWindow: "Today · 8:00 – 10:00 AM",
    dropoffWindow: "Thu · 6:00 – 8:00 PM",
    pickupNote: "Pickup at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "Yesterday, 8:42 pm",
    },
    leaveBagsOutside: true,
    cancellable: true,
  },
  {
    orderId: "CUI411",
    orderType: "laundry",
    status: "pickup_in_progress",
    listTimestamp: "Today, 7:42 am",
    pickupLocation: "Apt 1208, Marina Promenade, Dubai Marina",
    pickupWindow: "Today · 7:00 – 9:00 AM",
    dropoffWindow: "Thu · 5:00 – 7:00 PM",
    pickupNote: "Pickup at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "Yesterday, 7:14 pm",
    },
  },
  {
    orderId: "CUI412",
    orderType: "laundry",
    status: "dropoff_assigned",
    listTimestamp: "Today, 2:14 pm",
    pickupLocation: "Apt 1502, Damac Heights, Dubai Marina",
    pickupWindow: "19 Apr · 8:00 – 10:00 AM",
    dropoffWindow: "Today · 5:00 – 7:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "18 Apr, 7:30 pm",
      collected: "19 Apr, 8:24 am",
      items_in_process: "19 Apr, 1:08 pm",
    },
  },
  {
    orderId: "CUI415",
    orderType: "laundry",
    status: "dropoff_failed",
    listTimestamp: "Today, 6:42 pm",
    pickupLocation: "Villa 14, Al Sufouh, Jumeirah",
    pickupWindow: "18 Apr · 7:00 – 9:00 AM",
    dropoffWindow: "Today · 5:00 – 7:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Hand to resident",
    stageTimestamps: {
      received: "17 Apr, 8:12 pm",
      collected: "18 Apr, 7:28 am",
      items_in_process: "18 Apr, 12:48 pm",
      delivery_today: "Today, 4:30 pm",
      driver_on_the_way: "Today, 5:48 pm",
    },
  },
  {
    orderId: "PND472",
    orderType: "laundry",
    status: "pending_items_delivery_followup",
    listTimestamp: "Awaiting follow-up drop off",
    pickupLocation: "Apt 1208, Sky Gardens, DIFC",
    pickupWindow: "20 Apr · 7:00 – 9:00 AM",
    dropoffWindow: "Today · before 8:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Drop off at door",
    stageTimestamps: {
      received: "19 Apr, 6:55 pm",
      collected: "20 Apr, 7:42 am",
      items_in_process: "20 Apr, 12:30 pm",
      delivery_today: "22 Apr, 4:10 pm",
      complete: "22 Apr, 6:18 pm",
    },
    itemsPending: 3,
  },
  {
    orderId: "LBR219",
    orderType: "laundry_bag",
    status: "laundry_bag_requested",
    listTimestamp: "Requested on 23 Apr 2026, 10:08 AM",
    pickupLocation: "Apt 706, Bay Square, Business Bay",
    pickupWindow: "Tomorrow · 10:00 AM – 12:00 PM",
    dropoffWindow: "Tomorrow · 10:00 AM – 12:00 PM",
    stageTimestamps: {
      received: "23 Apr, 10:08 am",
    },
  },

  // --- Past orders ---
  {
    orderId: "CUI392",
    orderType: "laundry",
    status: "dropoff_completed",
    listTimestamp: "Completed on 22 Apr 2026, 12:41 PM",
    pickupLocation: "Apt 712, JLT Cluster G",
    pickupWindow: "18 Apr · 8:00 – 10:00 AM",
    dropoffWindow: "22 Apr · 12:00 – 2:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Delivered at door",
    stageTimestamps: {
      received: "17 Apr, 7:20 pm",
      collected: "18 Apr, 8:32 am",
      items_in_process: "18 Apr, 1:05 pm",
      delivery_today: "22 Apr, 11:20 am",
      complete: "22 Apr, 12:41 pm",
    },
  },
  {
    orderId: "CTN375",
    orderType: "laundry",
    status: "dropoff_completed",
    listTimestamp: "Completed on 5 Apr 2026, 2:39 PM",
    pickupLocation: "Apt 304, Al Barsha Heights",
    pickupWindow: "1 Apr · 7:00 – 9:00 AM",
    dropoffWindow: "5 Apr · 1:00 – 3:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Delivered at door",
    stageTimestamps: {
      received: "31 Mar, 8:14 pm",
      collected: "1 Apr, 7:38 am",
      items_in_process: "1 Apr, 12:10 pm",
      delivery_today: "5 Apr, 1:20 pm",
      complete: "5 Apr, 2:39 pm",
    },
  },
  {
    orderId: "CRC070",
    orderType: "finery",
    status: "dropoff_completed",
    listTimestamp: "Completed on 17 Feb 2026, 7:32 PM",
    pickupLocation: "Villa 12, Palm Jumeirah",
    pickupWindow: "13 Feb · 9:00 – 11:00 AM",
    dropoffWindow: "17 Feb · 6:00 – 8:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Delivered at door",
    stageTimestamps: {
      received: "12 Feb, 9:02 pm",
      collected: "13 Feb, 9:24 am",
      items_in_process: "13 Feb, 2:10 pm",
      delivery_today: "17 Feb, 6:00 pm",
      complete: "17 Feb, 7:32 pm",
    },
  },
  {
    orderId: "LBG552",
    orderType: "laundry_bag",
    status: "laundry_bag_delivered",
    listTimestamp: "Delivered on 22 Apr 2026, 11:08 AM",
    pickupLocation: "Apt 1402, Marina Heights, Dubai Marina",
    pickupWindow: "22 Apr · 9:00 – 11:00 AM",
    dropoffWindow: "22 Apr · 9:00 – 11:00 AM",
    stageTimestamps: {
      received: "21 Apr, 9:42 pm",
      complete: "22 Apr, 11:08 am",
    },
  },
  {
    orderId: "CSO663",
    orderType: "laundry",
    status: "dropoff_completed",
    listTimestamp: "Completed on 13 Mar 2026, 4:31 PM",
    pickupLocation: "Apt 808, Dubai Hills Estate",
    pickupWindow: "9 Mar · 8:00 – 10:00 AM",
    dropoffWindow: "13 Mar · 3:00 – 5:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Delivered at door",
    stageTimestamps: {
      received: "8 Mar, 7:40 pm",
      collected: "9 Mar, 8:18 am",
      items_in_process: "9 Mar, 12:55 pm",
      delivery_today: "13 Mar, 3:10 pm",
      complete: "13 Mar, 4:31 pm",
    },
  },
  {
    orderId: "CTB988",
    orderType: "laundry",
    status: "dropoff_completed",
    listTimestamp: "Completed on 25 Mar 2026, 7:47 PM",
    pickupLocation: "Apt 506, City Walk",
    pickupWindow: "21 Mar · 6:00 – 8:00 PM",
    dropoffWindow: "25 Mar · 6:00 – 8:00 PM",
    pickupNote: "Picked up at door",
    dropoffNote: "Delivered at door",
    stageTimestamps: {
      received: "20 Mar, 8:24 pm",
      collected: "21 Mar, 6:32 pm",
      items_in_process: "22 Mar, 10:18 am",
      delivery_today: "25 Mar, 6:30 pm",
      complete: "25 Mar, 7:47 pm",
    },
  },
  {
    orderId: "CNX331",
    orderType: "laundry",
    status: "order_cancelled",
    listTimestamp: "Cancelled on 14 Apr 2026, 9:22 AM",
    pickupLocation: "Apt 1108, Vision Tower, Business Bay",
    pickupWindow: "14 Apr · 11:00 AM – 1:00 PM",
    dropoffWindow: "18 Apr · 4:00 – 6:00 PM",
    stageTimestamps: {
      received: "13 Apr, 7:18 pm",
    },
    cancelledAt: "Today at 2:41 PM",
    cancelReason: "pickup_failed",
  },
];

export const MOCK_ACTIVE_ORDERS = MOCK_ORDERS.filter(
  (o) => STATUS_TO_CATEGORY[o.status] !== "completed",
);

export const MOCK_PAST_ORDERS = MOCK_ORDERS.filter(
  (o) => STATUS_TO_CATEGORY[o.status] === "completed",
);

export const findOrderById = (orderId: string): OrderData | undefined =>
  MOCK_ORDERS.find((o) => o.orderId === orderId);

/** Default fallback for detail pages hit without route state (direct URL / refresh / Demo gallery). */
export const FALLBACK_ORDER: OrderData = MOCK_ORDERS[0];
